#!/bin/bash

#COLOURS 

green="\e[0;32m"
end="\e[0;0m"
red="\e[0;31m"
gray="\e[0;37"
yellow="\e[0;33m"
blue="\e[0;34m"

if [[ $1 == "-i" && $2 =~ [0,9]{1,5} ]]; then

	echo "$(tput setaf 12)_________________________________________"
        echo "|                                       |"
        echo "|        Sxmpl3 rangeScan v1.0          |"
        echo "|                                       |"
        echo "|      https://github.com/Sxmpl3/       |"
        echo "|_______________________________________|"
        echo "$(tput setaf 2) "
        echo ""
        sleep 1s
        echo -e "\n ${yellow}[+]${end} Escaneando Hosts activos..."
        echo ""


	for h in $(seq 2 254); do
		timeout 1 bash -c "ping -c 1 $2.$h > /dev/null 2>&1" && echo -e "\n ${yellow}[/]${end} Host ${yellow}$2.$h${end} - ACTIVO" &
	done; wait

	echo ""
	echo -e  "\n ${yellow}[-]${end} Escaneo finalizado."

	exit 1


else

        echo "$(tput setaf 12)_________________________________________"
        echo "|                                       |"
        echo "|        Sxmpl3 rangeScan v1.0          |"
        echo "|                                       |"
        echo "|      https://github.com/Sxmpl3/       |"
        echo "|_______________________________________|"
        echo "$(tput setaf 2) "
        echo "[ HOW TO USE ]"
	echo ""
	echo "rangeScan -i (address without host = 192.168.1)"

	exit 1

fi
